#!/usr/bin/env bash
#Challenge
check_factor()
{
	if [ $# -ne 3 ];
	then
		args=("$@")
		s=0
		n=1
		for a in ${args[*]};
		do
			if [ $count -gt 1 ];
			then
				n=$(echo $a*$n | bc)
			fi
			s=$((s + 1))
		done
	else
		n=$3
	fi

	num1=$2
	num=$(echo "$1" | tr ':' '=')
	
	result=$(echo "if($n > $num1) 1 else 0" | bc)
		if ((result == 1)); then
			numcp=$num1
			num1=$n
			n=$numcp
		fi
	
	echo "$num$num1*$n"
}

if [ $# -ne 1 ]
then
	echo 'Usage: rsa <file>'
	exit 1
else
	
	while read i
	do
		
		result=$(factor "$i")
		check_factor $result
	done < "$1"

fi
